version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r backend/requirements.txt
  build:
    commands:
      - docker build -t latest .
      - export PYTHONPATH=.
      - pytest backend/tests/
